---
apiVersion: v1
kind: Namespace
metadata:
  name: ${K8S_NAMESPACE}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics-poller
  labels:
    app: metrics-poller
  namespace: ${K8S_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-poller
  template:
    metadata:
      labels:
        app: metrics-poller
    spec:
      terminationGracePeriodSeconds: 15
      containers:
      - name: metrics-poller
        image: ${REGISTRY}/${CI_PROJECT_PATH_SLUG}/metrics-poller:${CI_PIPELINE_ID}
        resources:
          limits:
            cpu: 0.5
          requests:
            cpu: 0.2
            memory: 50Mi
        env:
        - name: AWS_ACCESS_KEY_ID
          value: ${KOPS_AWS_KEY}
        - name: AWS_SECRET_ACCESS_KEY
          value: ${KOPS_AWS_SECRET}
        - name: K8S_CLUSTER_REGION
          value: ${K8S_CLUSTER_REGION}
        - name: KOPS_STATE_STORE
          value: ${KOPS_STATE_STORE}
        - name: K8S_CLUSTER_NAME
          value: ${K8S_CLUSTER_NAME}
        - name: METRIC_INTERVAL
          value: "150"
        - name: K8S_NAMESPACE_EXCLUDE
          value: "gitlab default kube-system"
      priorityClassName: high-priority
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
